# Dockerfile
FROM python:3.9.13

# Definir os argumentos do build
ARG BUCKET_NAME
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG ENDPOINT_NAME
ARG PORT
ARG DB_NAME
ARG USER
ARG PASSWORD
ARG DW_SCHEMA_TO_CREATE
ARG DW_TEMP_SCHEMA_TO_CREATE
ARG PROCESSED_TABLE_NAME
ARG FROM
ARG TO
ARG EMAIL_PASS

# Definir as variáveis de ambiente com os valores dos argumentos do build
ENV BUCKET_NAME=$BUCKET_NAME
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
ENV AWS_REGION=$AWS_REGION
ENV ENDPOINT_NAME=$ENDPOINT_NAME
ENV PORT=$PORT
ENV DB_NAME=$DB_NAME
ENV USER=$USER
ENV PASSWORD=$PASSWORD
ENV DW_SCHEMA_TO_CREATE=$DW_SCHEMA_TO_CREATE
ENV DW_TEMP_SCHEMA_TO_CREATE=$DW_TEMP_SCHEMA_TO_CREATE
ENV PROCESSED_TABLE_NAME=$PROCESSED_TABLE_NAME
ENV FROM=$FROM
ENV TO=$TO
ENV EMAIL_PASS=$EMAIL_PASS

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os arquivos para o contêiner
COPY . /app

# Instalar os pacotes necessários
RUN pip install -r requirements.txt

# Rodar o script em questão
ENTRYPOINT python3 main.py
